# Generated by Django 5.2.17 on 2026-08-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='proj_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='proj_videos/'),
        ),
    ]
