# Generated by Django 5.2.17 on 2026-08-22 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_category_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approach',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='business_impact',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='results',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('DATA_ANALYTICS', 'Data_Analytics'), ('MACHINE_LEARNING', 'Machine_Learning'), ('DJANGO', 'Django')], default='DATA_ANALYTICS', max_length=100),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
