# Generated by Django 5.2.17 on 2026-08-22 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_approach_project_business_impact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='videos',
            new_name='video',
        ),
    ]
