# Generated by Django 5.2.17 on 2026-08-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_videos_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('DT_ANALYTICS', 'Data_Analytics'), ('MCHINE_LEARNIN', 'Machine_Learning'), ('DJNGO', 'Django')], default='DT_ANALYTICS', max_length=100),
        ),
    ]
