# Generated by Django 5.2.17 on 2026-08-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('DT_ANALYTICS', 'Data Analytics'), ('MACHINE_LEARNING', 'Machine Learning'), ('DJANGO', 'Django')], default='DT_ANALYTICS', max_length=100),
        ),
    ]
